name:                find-reverse
version:             1.0.0
github:              "dotKuro/find-reverse"
license:             AGPL-3
author:              "Alexander Kampf"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/dotKuro/find-reverse#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- filepath
- containers

library:
  source-dirs: src

executables:
  find-reverse-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - find-reverse

tests:
  find-reverse-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - find-reverse
